### PR TITLE
chore: axoasset 0.10.0

### PR DESCRIPTION
**Pull request by mistydemeo**

### CODE REVIEW

**Comment by mistydemeo** [comment]
gazenot doesn't use the RemoteAsset feature of axoasset, which is the one that pulls in reqwest.

**Comment by Gankra** [comment]
Right, we should start using it (just to get a shared reqwest), as it pulls in minimal other deps, and it simplifies ensuring everything in our tree is using the same http stack.

**Comment by mistydemeo** [comment]
Done. Just noticed this slightly alters the features: we weren't using `gzip` as a reqwest feature in axoasset, but we were here, so it's now been removed from gazenot.

**Comment by Gankra** [comment]
Oh huh is that gonna be a big deal...

**Review by Gankra — APPROVED** [review]

**Comment by Gankra** [comment]
(we'll find out in testing in cargo-dist)

**Pull request merged**
